package goerror

const (
	// Informational
	CodeContinue           = "INF000"
	CodeSwitchingProtocols = "INF001"
	CodeProcessing         = "INF002"
	CodeEarlyHints         = "INF003"

	// Successful
	CodeOK                          = "SUC000"
	CodeCreated                     = "SUC001"
	CodeAccepted                    = "SUC002"
	CodeNonAuthoritativeInformation = "SUC003"
	CodeNoContent                   = "SUC004"
	CodeResetContent                = "SUC005"
	CodePartialContent              = "SUC006"
	CodeMultiStatus                 = "SUC007"
	CodeAlreadyReported             = "SUC008"
	CodeIMUsed                      = "SUC009"

	// Redirection
	CodeMultipleChoices   = "RED000"
	CodeMovedPermanently  = "RED001"
	CodeFound             = "RED002"
	CodeSeeOther          = "RED003"
	CodeNotModified       = "RED004"
	CodeUseProxy          = "RED005"
	CodeTemporaryRedirect = "RED007"
	CodePermanentRedirect = "RED008"

	// Client error
	CodeBadRequest                   = "CLE000"
	CodeUnauthorized                 = "CLE001"
	CodePaymentRequired              = "CLE002"
	CodeForbidden                    = "CLE003"
	CodeNotFound                     = "CLE004"
	CodeMethodNotAllowed             = "CLE005"
	CodeNotAcceptable                = "CLE006"
	CodeProxyAuthRequired            = "CLE007"
	CodeRequestTimeout               = "CLE008"
	CodeConflict                     = "CLE009"
	CodeGone                         = "CLE010"
	CodeLengthRequired               = "CLE011"
	CodePreconditionFailed           = "CLE012"
	CodeRequestEntityTooLarge        = "CLE013"
	CodeRequestURITooLong            = "CLE014"
	CodeUnsupportedMediaType         = "CLE015"
	CodeRequestedRangeNotSatisfiable = "CLE016"
	CodeExpectationFailed            = "CLE017"
	CodeTeapot                       = "CLE018"
	CodeMisdirectedRequest           = "CLE019"
	CodeUnprocessableEntity          = "CLE020"
	CodeLocked                       = "CLE021"
	CodeFailedDependency             = "CLE022"
	CodeTooEarly                     = "CLE023"
	CodeUpgradeRequired              = "CLE024"
	CodePreconditionRequired         = "CLE025"
	CodeTooManyRequests              = "CLE026"
	CodeRequestHeaderFieldsTooLarge  = "CLE027"
	CodeUnavailableForLegalReasons   = "CLE028"

	// Server error
	CodeInternalServerError           = "SVR000"
	CodeNotImplemented                = "SVR001"
	CodeBadGateway                    = "SVR002"
	CodeServiceUnavailable            = "SVR003"
	CodeGatewayTimeout                = "SVR004"
	CodeHTTPVersionNotSupported       = "SVR005"
	CodeVariantAlsoNegotiates         = "SVR006"
	CodeInsufficientStorage           = "SVR007"
	CodeLoopDetected                  = "SVR008"
	CodeNotExtended                   = "SVR009"
	CodeNetworkAuthenticationRequired = "SVR010"
)
